### PR TITLE
Check gPTP valid before enumerating device

### PR DESCRIPTION
**Pull request by vronchetti**

### CODE REVIEW

**Comment by ajwlucas** [comment]
Not sure I agree with this change - we should enumerate devices that don't support gPTP. Was this added to work around another issue?

**Comment by andrew-elder** [comment]
This change was made to prevent other AVDECC contollers showing up in the endstation list. I'm 100% open to a different solution if you would like to suggest one.

**Comment by ajwlucas** [comment]
I would suggest we instead check the talker_capabilities and listener_capabilities flags for IMPLEMENTED and if neither are set we don't enumerate.

**Comment by andrew-elder** [comment]
Ok, we'll make that change. Can you elaborate on the scenario where a device might have talker and listener capabilities, but not gPTP support? I'm missing some the thought process here.....

**Comment by ajwlucas** [comment]
I guess I'm thinking about new devices that can source or sink AVTP Control Format streams or vendor specific formats (new in 1722-2015) that are not required to support gPTP (or even SRP reservations..).

There's probably also a class of device that just implement AEM Controls and do not support any Talker or Listener capabilities (audio or control). Using the talker_capabilities and listener_capabilities flags here won't work. There's not really an ADP flag to cover this class of device either, so we would have to partially enumerate the device's Configuration descriptor(s) before deciding to display it or not...

The other option is to enumerate everything on the network and then do a post-enumeration filter on what shows up in the entity list. We have all the descriptors needed to make a good decision at that point.

**Comment by ajwlucas** [comment]
I think the library should probably do the general, wide-use case behaviour and leave it up to the application to filter. Some users might want Controllers to show up in their application and the library shouldn't prevent this.

**Comment by ajwlucas** [comment]
Which raises the point whether the library should offer the application a way of overriding what flags to fully enumerate on, in the case where you might want to minimise the enumeration time.

**Comment by andrew-elder** [comment]
One of the issues is that read of the ENTITY descriptor times out on a Riedel controller entity, so an application that chooses to show error messages will see a bunch of them attempts to interact (ie read) the Riedel controller's AEM descriptors.

**Comment by andrew-elder** [comment]
Having the user specify flags to check/filter when enumerating is a good soln. Great idea!

**Comment by ajwlucas** [comment]
Oh we shouldn't be enumerating devices that haven't got the AEM_SUPPORTED flag set. This might be enough to prevent the Riedel ENTITY descriptor time out issue.

**Comment by andrew-elder** [comment]
You would think  - except it does seem to set AEM_SUPPORTED (in error I believe). I'm going to go with allowing the user to optionally provide filter flags - or at least review how that would work....

**Comment by jdkoftinoff** [comment]
If an entity is sending ADP with AEM_SUPPORTED then it had better support AEM, which requires at least READ_DESCRIPTOR. Otherwise it is broken. In addition, if it supports AEM and receives an AEM COMMAND that it does not support, it had better respond to those commands with the status code of NOT_IMPLEMENTED.

The question remains: what to do with entities that misbehave? One option is to see if it times out 3 times in a row, then blacklist it and run as if the entity did not exist.

Do you handle the case of GENERAL_CONTROLLER_IGNORE being set?

Please don’t ignore devices that are responders. I have a lot of them! they do not use gPTP or streams, but have a full entity model.  For one product, the control plane needs to work for SET/GET CONTROL even when AVB is not available, because the user might be selecting analog or AES3 inputs.

**Comment by andrew-elder** [comment]
Will make sure responders work.....

My not get the fix in place until early next week. Thanks for your response.

No, I don't think we handle GENERAL_CONTROLLER_IGNORE. Will have to check 
the code base.

Yes, that is a good question about how to handle mi-behaving entities. Will 
create a separate issue for it.

On 8/7/2015 10:54 AM, Jeff Koftinoff wrote:
> If an entity is sending ADP with AEM_SUPPORTED then it had better support 
> AEM, which requires at least READ_DESCRIPTOR. Otherwise it is broken. In 
> addition, if it supports AEM and receives an AEM COMMAND that it does not 
> support, it had better respond to those commands with the status code of 
> NOT_IMPLEMENTED.
>
> The question remains: what to do with entities that misbehave? One option 
> is to see if it times out 3 times in a row, then blacklist it and run as 
> if the entity did not exist.
>
> Do you handle the case of GENERAL_CONTROLLER_IGNORE being set?
>
> Please don’t ignore devices that are responders. I have a lot of them! 
> they do not use gPTP or streams, but have a full entity model. For one 
> product, the control plane needs to work for SET/GET CONTROL even when 
> AVB is not available, because the user might be selecting analog or AES3 
> inputs.
>
>
>
> > On Aug 7, 2015, at 07:26, andrew-elder <notifications@github.com> wrote:
> >
> > You would think - except it does seem to set AEM_SUPPORTED (in error I 
> believe). I'm going to go with allowing the user to optionally provide 
> filter flags - or at least review how that would work....
> >
> > —
> > Reply to this email directly or view it on GitHub 
> <https://github.com/audioscience/avdecc-lib/pull/219#issuecomment-128714042>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/audioscience/avdecc-lib/pull/219#issuecomment-128721685>.
>


-- 
Andrew Elder
AudioScience, Inc.
+1-585-271-8870
www.audioscience.com

**Comment by andrew-elder** [comment]
Latest merge allows user (application) to pass in a set of flags to set any filter they wish.

**Pull request merged**
