### PR TITLE
Minor fixes to command line app

### PR DESCRIPTION
**Pull request by ahogen**
A few `avdecccmdline` annoyances fixed here. Most significant commit is: https://github.com/ahogen/avdecc-lib/commit/43dd87e7cd93f722a127df25942c3e84129b57c6 where some command line segfaults were (based on my limited testing) fixed.

Critiques and comments welcome.

### CODE REVIEW

**Comment by andrew-elder** [comment]
@ahogen - changes all look good thanks. Do you mind signing the CLA (see clahub above) before I merge these changes across. Thanks again.

**Comment by andrew-elder** [comment]
Oops, clahub bleow...

**Comment by ahogen** [comment]
Certainly. I saw that during my last PR. I'll check with my boss first, but I wouldn't think there would be any problems.

**Comment by andrew-elder** [comment]
@ahogen - any updates on the CLA?

**Comment by ahogen** [comment]
@andrew-elder I did ask a couple days ago. My boss doesn't have an particular issues with it. Seems like just the standard stuff, with the repo being under MIT and all. However, this needs to be presented to others in our company who deal with more legal issues and I can't speak for what their decision will be. Sometimes statements like "Grant of Patent License" bothers people. I would hope I will get approval, but my opinion doesn't matter here and so I can't say.

**Comment by andrew-elder** [comment]
Ok, thanks for the update. Sorry if this slowed everything down for you. I may just optionally merge your change anyway if you don't hear anything back next week - but that kind of defeats the purpose of the whole thing.

**Comment by ahogen** [comment]
No, it's just fine. I understand why you'd want to do this. I'm suprised AVnu/Intel/whoever hasn't done this in OpenAVB since there are so many contributing companies and individuals. 

I'll be sure to give you an update whenever I hear back.

**Comment by ahogen** [comment]
I will go ahead and sign this as an individual, independent of any company or organization.

**Pull request merged**
